FROM python:3.6

USER root

ARG USER=python_user
RUN useradd -ms /bin/bash $USER

ADD ./requirements_scripts.txt /home/$USER/requirements_scripts.txt
RUN pip3 install -r /home/$USER/requirements_scripts.txt

USER $USER
WORKDIR /home/$USER
